#the project name
site_name: lfp documents
#the project access address
dev_addr: localhost:10086

# Repository
repo_name: lfp_tech_advance
repo_url: https://github.com/Lee91/lfp_tech_advance
edit_uri: ""
site_author: wytaitaislee

site_description: >-
  保持技术热情，将所见所闻探本溯源。</br>
  一方面拓实基础，另一方面学习优秀开源项目的架构思想，不断提升自己的技术视野


# Copyright
copyright: Copyright &copy; 2019 - 2022 wytaitaislee

#pages layout
nav:
- 主页: index.md
- 介绍: introduction/introduction.md
- 基础组件:
    - logs: util/util_logs.md
- 系统抽象:
    - arch: arch/arch.md
    - arch adapter: arch_adapter/arch_adapter.md
- 应用服务:
    - 关于: app_base/app_base.md
    - 算法: 
        - 排序算法: app_base/app_algo/app_algo_sort/app_algo_sort.md
    - 用户层busybox: app_base/app_busybox/app_busybox.md
    - 封装库: 
        - 单向链表: app_base/app_libs/app_slist/app_slist.md
        - 双向链表: app_base/app_libs/app_dlist/app_dlist.md
        - 线程池: app_base/app_libs/app_threadpool/app_threadpool.md
        - 安全函数: app_base/app_libs/app_safec/app_safec.md
        - socket: app_base/app_libs/app_socket/app_socket.md
- 应用: 
    - 关于: app/app.md
- 更多:
    - 头文件组织原则:
        - include: include/include.md
    - 编译构建:
        - exec: exec/exec.md
        - linking: linking/linking.md
        - main: main/main.md
        - menuconfig: menuconfig/menuconfig.md
        - lfp_rules.make: rules.make/rules.make.md
    - 编码规范:
        - 编码规范: programming_rules/programming_rules.md
        - 工具: roadmapping/extensions/tools/stats_tools.md
    - 进阶: 
        - 进阶线路图: roadmapping/roadmapping.md
        - 扩展:
            - 通用知识: roadmapping/extensions/extensions.md
            - whiptail: roadmapping/extensions/whiptail/whiptail.md
            - markdown语法: roadmapping/extensions/markdown.md
#theme: readthedocs

# markdown extension
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - toc.integrate
  custom_dir: material
# 404 page
  static_templates:
    - 404.html
    
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  # 让浏览器的收藏夹中除显示相应的标题外，还以图标的方式区别不同的网站
  favicon: assets/github.svg
  # 网站页面中的图标(网站名前面的图标)
  icon:
    logo: github
    
# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto

extra:
  alternate:
    - name: English
      link: https://squidfunk.github.io/mkdocs-material-insiders/en/
      lang: en
    - name: Deutsch
      link: https://squidfunk.github.io/mkdocs-material-insiders/de/
      lang: de
    - name: 日本語
      link: https://squidfunk.github.io/mkdocs-material-insiders/jp/
      lang: jp
